### PR TITLE
Dependencies

### PR DESCRIPTION
**Pull request by pookaknight**
Lots have dependencies have significantly newer versions. This update will need to be tested thoroughly.

### CODE REVIEW

**Comment by pikemurdy** [comment]
A mistake was made on a push. The functions file is enqueuing `http://localhost:8888/utksds-framework/build/assets/css/style.css`

It should be enqueuing `https://images.utk.edu/designsystem/v1/latest/assets/css/style.css`

This is probably a mistake I just made.

**Comment by pookaknight** [comment]
I didn't edit any files other than package.json. That error must have already been on main.

**Comment by pikemurdy** [comment]
It must have been. We'll fix this in the future more-formal workflow.

**Comment by pookaknight** [comment]
Although that did make me notice a mistake on my part. Going to do another commit to fix it momentarily.

**Pull request merged**
